#!/usr/local/bin/perl  -T

################################################################################
#
# File:    status
# Date:    $Date: 2008-04-27 18:20:56 -0500 (Sun, 27 Apr 2008) $
# Version: $Revision: 129 $
#
# Print the status of all jobs that are scheduled to run today.                 
#
################################################################################

use strict;
use warnings;
use TaskForest;


my $task_forest = TaskForest->new(TF_JOB_DIR => "unnecessary", TF_RUN_WRAPPER=>"unnecessary");
$task_forest->status();




