#!/usr/local/bin/perl  -T

################################################################################
#
# $Id$
#
# Print the status of all jobs that are scheduled to run today.                 
#
################################################################################

use strict;
use warnings;
use TaskForest;


my $task_forest = TaskForest->new(TF_JOB_DIR => "unnecessary", TF_RUN_WRAPPER=>"unnecessary");
$task_forest->status();




